### PR TITLE
Adds a new theme: Wasteland, inspired by the oldschool Fallout Pipboy.

### PR DESCRIPTION
**Pull request by bernig**

### CODE REVIEW

**Review by Aemiii91 — APPROVED** [review]

**Comment by nixhugger** [comment]
Hello @bernig, love your theme. found a bug in soft shutdown menu. when shutting down via `settings >> shutdown`, menu options for `A` = `YES` and `B` = `NO` does not show the text `YES` and `NO`. I can look into it and see if I can figure out what might be causing it. Just wanted to let you know in case you already can see what the issue might be.

**Comment by nixhugger** [comment]
attached is a screenshot.
MainUI_000

**Comment by nixhugger** [comment]
attached is a screenshot of expected behavior.
MainUI_001

**Comment by bernig** [comment]
Hi !
Thanks for your comment! If I remember correctly, this is not something I can fix at the theme level but I will look into it next week.

**Comment by nixhugger** [comment]
not sure why but it appears that the shutdown menu behavior is inconsistent across different themes. I haven't checked all themes but I noticed RetroRama does not have this issue, shows the text as expected. Second screenshot I posted is from the M by tenlevels, that person seem to be having the same issue and the work around being used there is to have the text as part of background image [(here).](https://github.com/OnionUI/Themes/blob/main/themes/M%20by%20tenlevels/skin/pop-bg.png) I will try to look into this myself, it could be something trivial.

**Pull request merged**
