### PR TITLE
update Cosy by KyleBing and add new icon pack Cosy

### PR DESCRIPTION
**Pull request by KyleBing**
- update `Cosy by KyleBing`, add game console icons and app icons
- add new icon pack `Cosy by KyleBing`

art-portrait-with-sign-3000w
preview-app-list

### CODE REVIEW

**Review by Aemiii91 — CHANGES_REQUESTED** [review]
Please remove all changes not in `themes/` or `icons/`. The workflow will generate the other things.

**Comment by KyleBing** [comment]
like this?

**Review by Aemiii91 — APPROVED** [review]
My bad. I apparently set up the automation to run on PRs as well 🤷‍♂️

**Comment by KyleBing** [comment]
Don't worry. I actually added those zips at the beginning.

**Pull request merged**
